# Generated by Django 2.1.7 on 2019-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrie',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='countrie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
