# Generated by Django 2.2 on 2019-08-01 02:22

from django.db import migrations, models
=======
# Generated by Django 2.1.7 on 2019-07-29 02:46

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> origin/develop


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('units', '0001_initial'),
>>>>>>> origin/develop
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id_chapter', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
<<<<<<< HEAD
=======
                ('id_unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unity')),
>>>>>>> origin/develop
            ],
        ),
    ]
