# Generated by Django 2.2.4 on 2019-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id_chapter', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
