# Generated by Django 2.1.7 on 2019-07-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='id_unity',
        ),
    ]
