# Generated by Django 2.2.4 on 2019-08-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('sections', '0001_initial'),
        ('years', '0001_initial'),
        ('kinds', '0001_initial'),
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Countrie')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinds.Kind')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='months.Month')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.Section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.Year')),
            ],
        ),
    ]
